name: sign_in
description: A new Flutter package project.
version: 0.1.0
homepage:

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  form_fields:
    path: ../../form_fields
  component_library:
    path: ../../component_library
  user_repository:
    path: ../../user_repository
  domain_models:
    path: ../../domain_models
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


